# Super level user permission
sudo: required

# Specific the language you are using
language: generic

# We need the docker cli pre installed'
services:
    - docker

# before_install are the command we want to execute before our test are ran
before_install:
    - docker build -t arigbedeomobolaji/docker_react -f Dockerfile.dev .

# the script section contains all the commands that need to be executed to actually run our test suite.

script:
    - docker run -e CI=true arigbedeomobolaji/docker_react npm run test

deploy:
    # deployment provider
    provider: elasticbeanstalk
    # Region it is serving from
    region: 'eu-west-2'
    # Name of our elastic beanstalk application
    app: 'Docker-react'
    # Name of created elastic beanstalk environment
    env: 'Dockerreact-env'
    # Name of Bucket where our code resides
    bucket_name: 'elasticbeanstalk-eu-west-2-386341442621'
    # name of the specific elastic beanstalk pplication
    bucket_path: 'Docker-react'
    # When we want to deploy actions to perform below means only deploy when a code is pushed to the main account.
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
